# Generated by Django 4.2.7 on 2023-12-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaexpress',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
