# Generated by Django 4.2.1 on 2023-10-10 07:26

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=webapp.models.dict_instance, verbose_name='mpesa_result')),
            ],
        ),
        migrations.CreateModel(
            name='LipaNaMpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, verbose_name='Transcation Type')),
                ('transcation_date', models.DateTimeField(verbose_name='Transcation date')),
                ('receipt_no', models.CharField(max_length=50, verbose_name='Mpesa Receipt Number')),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='reference number')),
                ('invoice_no', models.CharField(max_length=15, verbose_name='invoice number')),
                ('acc_balance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='account balance')),
                ('third_party', models.CharField(max_length=10, verbose_name='Third party ID')),
                ('phone', models.PositiveIntegerField(verbose_name='mobile phone number')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaExpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount')),
                ('receipt_no', models.CharField(max_length=100, verbose_name='Mpesa Receipt Number')),
                ('transcation_date', models.DateTimeField(verbose_name='Transcation Date')),
                ('phone', models.PositiveIntegerField(verbose_name='Phone Number')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
